services:
  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    container_name: lecture-devcontainer
    volumes:
      - ..:/workspaces/node-dev-env-lecture:cached
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
